version: "3.9"
   
services:
  stackqlsrv:
    image: stackql/stackql
    build:
      context: .
      cache_from: 
        - stackql/stackql
    command: 
      - bash
      - -c
      - 'stackql --auth=''{ "google": { "credentialsfilepath": "/opt/stackql/credentials/dummy/google/functional-test-dummy-sa-key.json", "type": "service_account" }, "okta": { "credentialsenvvar": "OKTA_SECRET_KEY", "type": "api_key" }, "github": { "type": "basic", "credentialsenvvar": "GITHUB_CREDS" }, "aws": { "type": "aws_signing_v4", "credentialsfilepath": "/opt/stackql/credentials/dummy/aws/functional-test-dummy-aws-key.txt", "keyID": "some-key-not-a-secret" }, "k8s": { "credentialsenvvar": "K8S_TOKEN", "type": "api_key", "valuePrefix": "Bearer " } }'' --registry=''{"url": "https://cdn.statically.io/gh/stackql/stackql-provider-registry/dev/providers"}}'' --pgsrv.tls=''{ "keyFilePath": "/opt/stackql/srv/credentials/pg_server_key.pem", "certFilePath": "/opt/stackql/srv/credentials/pg_server_cert.pem", "clientCAs": [ "''$$(base64 -w 0 /opt/stackql/srv/credentials/pg_client_cert.pem)''" ] }'' --pgsrv.address=0.0.0.0 --pgsrv.port=${PG_SRV_PORT_MTLS:-5476} srv'
    volumes:
      - ./keys:/opt/stackql/keys:ro
      - ./vol/srv/credentials:/opt/stackql/srv/credentials:ro
      - ./test/assets/credentials/dummy:/opt/stackql/credentials/dummy:ro
      - ./test/assets/input:/opt/stackql/input:ro
      - ${REGISTRY_SRC:-./test/registry-mocked}:/opt/stackql/registry:ro
      - ./vol/stackql/config:/opt/stackql/.stackql:rw 
    ports:
      - "${PG_SRV_PORT_DOCKER_MTLS:-5576}:${PG_SRV_PORT_MTLS:-5476}/tcp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OKTA_SECRET_KEY=${OKTA_SECRET_STR:-some-junk}
      - GITHUB_SECRET_KEY=${GITHUB_SECRET_STR:-some-junk}
      - K8S_SECRET_KEY=${K8S_SECRET_STR:-some-junk}
  credentialsgen:
    image: stackql/stackqlsrvcertificates
    build:
      context: .
      cache_from: 
        - stackql/stackql
        - stackql/stackqlsrvcertificates
      target: certificates
    volumes:
      - ./vol/srv/credentials:/opt/stackql/srv/credentials:rw
    command: 
      - bash
      - -c
      - |
        openssl req -x509 -keyout /opt/stackql/srv/credentials/pg_server_key.pem -out /opt/stackql/srv/credentials/pg_server_cert.pem  -config /opt/test/stackql/test/server/mtls/openssl.cnf -days 365 \
        && openssl req -x509 -keyout /opt/stackql/srv/credentials/pg_client_key.pem -out  /opt/stackql/srv/credentials/pg_client_cert.pem  -config /opt/test/stackql/test/server/mtls/openssl.cnf -days 365 \
        && openssl req -x509 -keyout /opt/stackql/srv/credentials/pg_rubbish_key.pem -out /opt/stackql/srv/credentials/pg_rubbish_cert.pem -config /opt/test/stackql/test/server/mtls/openssl.cnf -days 365