version: "3.9"
   
services:
  postgres_external_data_source:
    image: postgres:14.5-bullseye
    hostname: postgres_external_data_source
    environment:
      - POSTGRES_PASSWORD=stackql
      - POSTGRES_USER=stackql
    ports:
      - "8432:5432/tcp"
